### ISSUE TITLE
BetterNether Incompatibility?

### ISSUE THREAD

**Issue by Phrog42** [magistermaks/mod-stylishoccult#8]
Issue seems to be caused by interaction between BetterNether plants and Stylish Occult corruption generation.

> net.minecraft.class_148: Exception ticking world
> 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:911) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[client-intermediary.jar:?]
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
> 	at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{betternether:feather_fern}
> 	at net.minecraft.state.State.with(State:117) ~[?:?]
> 	at net.darktree.stylishoccult.block.occult.LeavesFleshBlock.getStateToFit(LeavesFleshBlock.java:46) ~[stylish-occult-0.12.0.jar:?]
> 	at net.darktree.stylishoccult.utils.OccultHelper.getCorruptionForBlock(OccultHelper.java:162) ~[stylish-occult-0.12.0.jar:?]
> 	at net.darktree.stylishoccult.utils.OccultHelper.spawnCorruption(OccultHelper.java:114) ~[stylish-occult-0.12.0.jar:?]
> 	at net.darktree.stylishoccult.utils.OccultHelper.corrupt(OccultHelper.java:73) ~[stylish-occult-0.12.0.jar:?]
> 	at net.darktree.stylishoccult.utils.OccultHelper.corruptAround(OccultHelper.java:40) ~[stylish-occult-0.12.0.jar:?]
> 	at net.darktree.stylishoccult.block.occult.FleshBlock.randomTick(FleshBlock.java:28) ~[stylish-occult-0.12.0.jar:?]
> 	at net.minecraft.block.AbstractBlock$AbstractBlockState.randomTick(AbstractBlock:923) ~[?:?]
> 	at net.minecraft.server.world.ServerWorld.redirect$eab000$redirectBlockStateTick(ServerWorld:10671) ~[?:?]
> 	at net.minecraft.server.world.ServerWorld.tickChunk(ServerWorld:486) ~[?:?]
> 	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:378) ~[?:?]
> 	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:322) ~[?:?]
> 	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:311) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907) ~[client-intermediary.jar:?]
> 	... 5 more
> 

> Description: Exception ticking world
> 
> java.lang.IllegalArgumentException: Cannot set property class_2758{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{betternether:feather_fern}
> 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
> 	at net.minecraft.state.State.with(State:117)
> 	at net.darktree.stylishoccult.block.occult.LeavesFleshBlock.getStateToFit(LeavesFleshBlock.java:46)
> 	at net.darktree.stylishoccult.utils.OccultHelper.getCorruptionForBlock(OccultHelper.java:162)
> 	at net.darktree.stylishoccult.utils.OccultHelper.spawnCorruption(OccultHelper.java:114)
> 	at net.darktree.stylishoccult.utils.OccultHelper.corrupt(OccultHelper.java:73)
> 	at net.darktree.stylishoccult.utils.OccultHelper.corruptAround(OccultHelper.java:40)
> 	at net.darktree.stylishoccult.block.occult.FleshBlock.randomTick(FleshBlock.java:28)
> 	at net.minecraft.block.AbstractBlock$AbstractBlockState.randomTick(AbstractBlock:923)
> 	at net.minecraft.server.world.ServerWorld.redirect$eab000$redirectBlockStateTick(ServerWorld:10671)
> 	at net.minecraft.server.world.ServerWorld.tickChunk(ServerWorld:486)
> 	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:378)
> 	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:322)
> 	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:311)
> 	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
> 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
> 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
> 	at java.lang.Thread.run(Thread.java:833)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.class_2688.method_11657(class_2688.java:117)
> 	at net.darktree.stylishoccult.block.occult.LeavesFleshBlock.getStateToFit(LeavesFleshBlock.java:46)
> 	at net.darktree.stylishoccult.utils.OccultHelper.getCorruptionForBlock(OccultHelper.java:162)
> 	at net.darktree.stylishoccult.utils.OccultHelper.spawnCorruption(OccultHelper.java:114)
> 	at net.darktree.stylishoccult.utils.OccultHelper.corrupt(OccultHelper.java:73)
> 	at net.darktree.stylishoccult.utils.OccultHelper.corruptAround(OccultHelper.java:40)
> 	at net.darktree.stylishoccult.block.occult.FleshBlock.method_9514(FleshBlock.java:28)
> 	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:923)
> 	at net.minecraft.class_3218.redirect$eab000$redirectBlockStateTick(class_3218.java:10671)
> 	at net.minecraft.class_3218.method_18203(class_3218.java:486)
> 	at net.minecraft.class_3215.method_14161(class_3215.java:378)
> 	at net.minecraft.class_3215.method_12127(class_3215.java:322)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:311)

**Comment by magistermaks** [comment]
Fixed in 0e671542554096166201a9018768cd98d5322ecf, will be a part of Stylish Occult 0.12.1

**Comment by magistermaks** [comment]
Apparently i did a fucky-wacky and this was still broken, fixed for real in 498b32e7cb6fc0d723c7d72ae7e8698ab7ba9860
gonna be a part of 0.12.2

**Comment by NerjalNosk** [comment]
And here I was wondering if someone already reported it, got kinda worried when it still crashed with the 0.12.1 version (I was originally using the 0.12.0 version)... Glad it is fixed for good. Can we know when will that new version be released? (Approximately, of course)

**Comment by magistermaks** [comment]
yeah sorry it takes so long, i had some irl stuff going, it should be out very soon
it also includes some balancing changes so i didn't want to rush it

**Comment by NerjalNosk** [comment]
Eyyyy it's fixed! Thanks a lot!
